Regexp only beginning of the line
voxpupuli/puppet-rvm pull request #124
Opened 2016-07-08 07:53 UTC by ernetas

I was constantly running into issues when using this Puppet module (using `puppet apply`) inside a Ruby project folder containing `.ruby-version` file. RVM parses this file while checking what version of Ruby it should use and sadly, it also does that while running `/usr/local/rvm/bin/rvm`. The problem is that, if Ruby version defined in `.ruby-version` is not installed, current version of RVM Puppet module will not detect that, because calling `/usr/local/rvm/bin/rvm` from inside a Ruby project folder would give something like this:
```
ernestas@vbox-ubuntu:~/ss$ /bin/sh -c '/usr/local/rvm/bin/rvm list strings'
ruby-2.3.0 is not installed.
To install do: 'rvm install ruby-2.3.0'
ernestas@vbox-ubuntu:~/ss$ 
```
Not only that, it can produce other warnings like:
```
$ rvm list strings
Warning! PATH is not properly set up, '/usr/local/rvm/gems/ruby-2.3.1/bin' is not at first place,
         usually this is caused by shell initialization files - check them for 'PATH=...' entries,
         it might also help to re-add RVM to your dotfiles: 'rvm get stable --auto-dotfiles',
         to fix temporarily in this shell session run: 'rvm use ruby-2.3.1'.
ruby-2.3.1
$ 
```
Sadly, not all of the warnings go to stderr, thus, it's not an option to just ignore stderr. We need to check for Ruby versions only from the beginning of a line.

2016-07-08 17:20 UTC, TJM commented
I assume a bug has already been filed against RVM for that? (not that we don't need to workaround it too)

2022-07-06 13:17 UTC, ekohl requested changes
I realize this is an ancient PR, but I'm going through old PRs. If you're still interested in this, I'd be happy to get this in.

2022-07-06 13:17 UTC, ekohl commented on lib/puppet/provider/rvm_system_ruby/rvm_system_ruby.rb
> +        line =~ Regexp.new(/^resource[:name]$/)
If you're going to match the whole line, why not simplify it to
```suggestion
        line == resource[:name]
```

And if you go that far, you can reduce it to
```ruby
rvmcmd("list", "strings").split("\n").include?(resouce[:name])

2022-07-07 09:45 UTC, ekohl commented on lib/puppet/provider/rvm_system_ruby/rvm_system_ruby.rb
> +        line =~ Regexp.new(/^resource[:name]$/)
Submitted as https://github.com/voxpupuli/puppet-rvm/pull/183

2022-07-07 10:14 UTC, ekohl commented
This would create a regression so I'm going to close this.

2022-07-07 10:14 UTC, closed without merging